version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: always

  searxng:
    image: searxng/searxng
    restart: always
    environment:
      - BASE_URL=http://localhost:8888/
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8888:8080"
    depends_on:
      - searxng

